test("test입니다",function(){
	raises(function(){
		throwException();
	},"예외상황 테스트");
});